name: "CI"

on: [push, pull_request]

jobs:
  android-build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Set up environment
        run: |
          chmod +x gradlew

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

  ios-build-debug:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu

      - name: Build App
        run: |
          xcodebuild -project ./iosApp/iosApp.xcodeproj -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: iOS tests
        # Disable CC due to https://github.com/google/ksp/issues/1463
        run: ./gradlew iosSimulatorArm64Test --no-configuration-cache
